version: "3.3"

services:

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:${ELASTIC_VERSION:-6.3.2}
    # https://github.com/docker/swarmkit/issues/1951
    hostname: packetbeat
    user: root
    networks:
      - elastic
      # - host
    configs:
      - source: pb_config
        target: /usr/share/packetbeat/packetbeat.yml
    volumes:
      - packetbeat:/usr/share/packetbeat/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - KIBANA_HOST=kibana
        #- ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
        #- KIBANA_HOST=${KIBANA_HOST:-node1}
    command: ["--strict.perms=false"]
    deploy:
      mode: global

networks:
  elastic:
    external: true
    # name: host

volumes:
  packetbeat:

configs:
  pb_config:
    file: ./elk/beats/packetbeat/config/packetbeat.yml
